pub const SHORTCUTS: &[(&str, &str)] = &[
    ("Esc", "Return to normal mode from an input"),
    ("i", "Insert mode: focus nearest input for the active pane"),
    ("/", "Insert mode in search"),
    ("Ctrl+h/l", "Move active pane left/right"),
    ("j/k", "Move down/up or scroll the active pane"),
    ("gg/G", "Top/bottom of the active pane"),
    ("Ctrl+d/u", "Half page down/up"),
    ("Enter", "Open selected thread from the thread pane"),
    ("a", "Archive"),
    ("u", "Toggle unread"),
    ("f", "Toggle flagged"),
    ("t", "Trash"),
    ("s", "Spam"),
    ("z", "Undo last tag operation"),
    ("r", "Reply"),
    ("R", "Reply all"),
    ("c", "Compose"),
    ("F", "Forward"),
    ("v", "Toggle text/visual HTML view"),
    ("q", "Toggle quote collapse"),
    ("y/Y", "Copy message/thread id"),
    ("I", "Load/trust images button"),
    ("S", "Save draft in compose"),
    ("x", "Discard draft/changes in compose"),
    ("D", "Delete opened local draft in compose"),
    ("g i/u/f/s/d/a", "Inbox/Unread/Flagged/Sent/Drafts/All"),
    (
        "Message menu",
        "Choose which message in the thread is selected",
    ),
    ("View menu", "Show text, HTML, headers, or raw source"),
    (
        "Copy menu",
        "Copy message/thread ids and selected message fields",
    ),
    (
        "Attachment right-click",
        "Save or open selected thread attachment",
    ),
    ("Ctrl+K", "Command palette"),
    ("Ctrl+Enter", "Send compose"),
    ("?", "Shortcuts overlay"),
];
