pub const SHORTCUTS: &[(&str, &str)] = &[
    ("Esc", "Return to normal mode from an input"),
    ("i", "Insert mode: focus nearest input for the active pane"),
    ("/", "Insert mode in search"),
    (":", "Open command entry; Tab completes commands"),
    ("Ctrl+h/l", "Move active pane left/right"),
    (
        "j/k",
        "Move selected thread down/up, or scroll the active pane",
    ),
    ("<count>j/k", "Move selected thread by count"),
    ("gg/G", "Top/bottom of the thread list or active pane"),
    ("<count>gg/G", "Load up to that thread number and select it"),
    (":nu/:nonu", "Show/hide thread numbers"),
    (
        "Ctrl+d/u",
        "Half page down/up through threads or active pane",
    ),
    ("Ctrl+f", "Load more thread results"),
    ("Enter", "Open selected thread from the thread pane"),
    ("a", "Archive"),
    ("u", "Toggle unread"),
    ("f", "Toggle flagged"),
    ("t", "Trash"),
    ("s", "Spam"),
    ("T t", "Add or remove one tag on selected messages"),
    ("T m", "Apply multiple tag changes, e.g. -inbox +books"),
    ("z z", "Undo last tag operation"),
    ("z m", "Open undoable tag-operation list"),
    ("r r", "Reply"),
    ("r a", "Reply all"),
    ("r f", "Forward"),
    ("r A", "Forward as attachment"),
    ("c", "Compose"),
    ("v", "Visual select threads from the thread pane"),
    ("V t/v/h/r", "Text/visual HTML/headers/raw view"),
    ("q", "Toggle quote collapse"),
    (
        "y m/t/f/o/c/s",
        "Copy message id/thread id/from/to/cc/subject",
    ),
    ("I", "Load/trust images button"),
    ("S", "Save draft in compose"),
    ("x", "Discard draft/changes in compose"),
    ("D", "Delete opened local draft in compose"),
    (
        "g i/u/f/s/d/t/a",
        "Inbox/Unread/Flagged/Sent/Drafts/Trash/All",
    ),
    ("g c 1-9", "Open numbered custom saved search"),
    (
        "g 1-9",
        "Open the numbered found-tag search or tag-path dropdown",
    ),
    (
        "Message menu",
        "Choose which message in the thread is selected",
    ),
    ("View menu", "Show text, HTML, headers, or raw source"),
    (
        "Copy menu",
        "Copy message/thread ids and selected message fields",
    ),
    (
        "Attachment right-click",
        "Save or open selected thread attachment",
    ),
    ("Ctrl+K", "Run command"),
    ("Ctrl+Enter", "Send compose"),
    ("?", "Shortcuts overlay"),
];
