[package]
name = "notm-app"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "notm"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
notm-mail = { path = "../notm-mail" }
notm-notmuch = { path = "../notm-notmuch" }
notm-test-support = { path = "../notm-test-support" }
notm-ui = { path = "../notm-ui" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
