[package]
name = "notm-mail"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
ammonia.workspace = true
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
chrono.workspace = true
email_address.workspace = true
html2text.workspace = true
libc.workspace = true
mailparse.workspace = true
quoted_printable.workspace = true
regex.workspace = true
serde.workspace = true
shell-words.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
